skycoin/skycoin.net

src/locales/en.js

Stronger Call to Actions

---

src/components/WhitepapersPage/components/Whitepapers/downloads.js

feat: add roadmap link

---

src/components/Home/components/Miner/Miner.js
src/locales/en.js
src/locales/ru.js
src/locales/zh.js

feat: add link to skywire post

---

src/components/WhitepapersPage/components/Whitepapers/downloads.js

feat: add branding assets

---

src/components/Button/Button.js
src/components/Home/components/Hero/components/Introduction/Introduction.js
src/components/Home/components/Roadmap/Roadmap.js
src/locales/en.js
src/locales/ru.js
src/locales/zh.js

add new buttons in hero section, add link to roadmap

---

src/locales/en.js
src/locales/ru.js
src/locales/zh.js

fix: title

---

public/index.html

feat: check if twitter loaded

---

src/components/Downloads/components/Assets/Assets.js
src/components/Downloads/components/Roadmap/Roadmap.js
src/components/DownloadsTable/DownloadsTable.js
src/components/WhitepapersPage/components/Whitepapers/Whitepapers.js

fix: add unique ids

---

package.json
public/index.html
src/components/Blog/Blog.js
src/components/Blog/index.js
src/components/Home/Home.js
src/components/Home/components/Hero/Hero.js
src/locales/en.js
src/locales/ru.js
src/locales/zh.js

feat: add parsing latests news from blog

---

src/components/Blog/Blog.js

feat: add border after blog

---

src/components/Footer/content.js
src/locales/en.js
src/locales/ru.js
src/locales/zh.js

closes #100 
closes #99 
closes #98

add new links to the footer

---

public/index.html
src/components/Footer/content.js
src/components/Home/components/Miner/Miner.js
src/components/MailingPage/MailingPage.js
src/components/MailingPage/index.js
src/components/Routes/Routes.js
src/locales/en.js
src/locales/ru.js
src/locales/zh.js

feat: add mailing page

---

src/components/Home/Home.js
src/components/Home/components/About/About.js
src/locales/en.js
src/locales/ru.js
src/locales/zh.js

feat: mainpage-restructuring

---

src/components/Footer/content.js
src/locales/en.js
src/locales/ru.js
src/locales/zh.js

feat: add new links to footer

---

src/components/Downloads/components/BBS/downloads.js
src/components/MarketsPage/components/MarketsList/MarketsList.js

feat: update bbs, remove from markets etc

---

sitemap.xml

When live ill add it in the search console.

added core sitemap (without blog which already has them) #207

---

src/components/Home/components/Press/Press.js

https://monosnap.com/file/uutDhbHuogHXaCY2rH9fUvwMxBnZYH

fix padding in Press component

---

src/components/ApplicationTable/ApplicationTable.js
src/components/Downloads/components/Wallet/downloads.js

- change order of listings
- add separator

downloads page updates

---

src/components/Home/components/Press/Press.js
src/components/Home/components/Wallet/Wallet.js
src/locales/en.js
src/locales/zh.js

1. [Update home page's blue section's headline](https://trello.com/c/FtwltejG/4-update-home-pages-blue-sections-headline)
2. [Remove horizontal rule](https://trello.com/c/fabbbuVs/6-remove-horizontal-rule)

Changed press text. Removed gallery bottom line.

---

package.json
public/skycoin.css
src/components/BuyFiatPage/BuyFiatPage.js
src/config.js
src/locales/en.js
src/locales/ko.js
src/locales/ru.js
src/locales/zh.js

- Add currency conversion to fiat page.
- Added Skycoin logo in Indacoin stylesheet.

Add currency conversion

---

src/components/ThankYouPage/ThankYouPage.js

- Prevent blinking when page is loading
- Redirect to home page after 3 seconds

Thank you page fix

---

src/components/Home/components/Hero/components/Slider/Slider.js
src/components/Home/components/Press/Press.js
src/components/JobsPage/JobsPage.js
src/locales/en.js

re-ordered the jobs order and make the partners logo and slider aligned to the center on mobile device view.

reordered jobs and center aligned logos and slider
